include: package:flutter_lints/flutter.yaml
linter:
  rules:
    use_key_in_widget_constructors: false
    camel_case_types: false
    annotate_overrides: false
    file_names: false
#    prefer_const_constructors: false
    library_private_types_in_public_api: false