name: XXX
description: XXX
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  atreeon_menu_flutter: ^0.1.0
  dartx: ^1.2.0
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  atreeon_get_child_size: ^0.1.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

