name: XXX
description: XXX
version: 0.0.1+1
  #a.b.c+d
    #d=documentation, package, ci or publishing change only (doesn't affect package user)
    #c=bug fix or a very minor change to package (text or layout)
    #b=new feature
#homepage: https://atreeon.com
#repository: https://github.com/atreeon/XXX
publish_to: 'none'

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dartx: ^1.2.0
  intl: ^0.17.0

dev_dependencies:
  test: ^1.24.2
  build_runner: ^2.3.3