name: XXX
description: XXX
version: 0.0.1+1
  #a.b.c+d
    #d=documentation, package, ci or publishing change only (doesn't affect package user)
    #c=bug fix or a very minor change to package (text or layout)
    #b=new feature
#homepage: https://atreeon.com
#repository: https://github.com/atreeon/XXX
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^5.0.5
  dartx: ^0.6.0
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  google_fonts: ^3.0.1
  atreeon_menu_flutter: ^0.1.0
  logging: ^1.1.0
  shared_preferences: ^2.0.13
  atreeon_datagrid_responsive: ^0.0.2+2
  adaptive_dialog: ^1.8.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # https://flutter.dev/assets-and-images/#resolution-aware
  # https://flutter.dev/assets-and-images/#from-packages
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  # see https://flutter.dev/custom-fonts/#from-packages