name: Dart CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  dart:2.19.6

    steps:
      - uses: actions/checkout@v2
      - name: Setup atreeon_find_replace
        working-directory: ./
        run: |
          dart pub get
      - name: Run tests atreeon_find_replace
        working-directory: ./
        run: dart pub run test
